set nocompatible

if has('win32')
  set runtimepath +=~/.vim
  set fileencodings=utf-8,gbk,utf-16le,cp1252,iso-8859-15,ucs-bom
  set termencoding=utf-8
  set encoding=utf-8
endif
set runtimepath +=~/.vim/config
set pyxversion=3

source ~/.vim/config/keymap.vim
source ~/.vim/config/plugin.vim

set hls "检索时高亮

filetype on

syntax enable
set fileencodings=utf-8,gb18030,gbk,gb2312,cp936
"隐藏菜单和工具条
set guioptions-=T
"显示行号
syn on
set number
set ai "自动缩进
set bs=2
set showmatch
set laststatus=2 "总是显示状态栏
set cursorline
set nowrap

set background=dark

"语法缩进
"set foldmehod=indent
set foldmethod=syntax

if has("gui_running")
  if has("gui_macvim")
    set macligatures
    set guifont=FiraCode\ Nerd\ Font\ Mono:h16
  elseif has("gui_win32")
    set guifont=Consolas:h16:cANSI
  endif    
endif

"以下为配置tab和缩进
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set list
set lcs=tab:>-,
set autoread "自动读取已经修改的文件

set ignorecase "检索时忽略大小写
set incsearch
set hls "检索时高亮
set foldmethod=syntax "代码折叠
set foldlevelstart=99
set pumheight=10 "自动提示的个数 10

" 配置插件和 keymap
call plugin#main()
call ConfigKeymap()
colorscheme dracula

au BufRead,BufNewFile Podfile set filetype=ruby

" 区分语言的一些配置
autocmd FileType lua setlocal et sta sw=2 sts=2

" 大文件关闭语法高亮(50M, 基本都是日志)
autocmd BufWinEnter * if line2byte(line("$") + 1) > 10000000 | syntax clear | endif
