set runtimepath+=~/.vim/config

set nocompatible
let mapleader = ' '

source ~/.vim/config/keymap.vim
source ~/.vim/config/plugin.vim

call ConfigPlugin()
set hls "检索时高亮

filetype on

syntax enable
set fileencodings=utf-8,gb18030,gbk,gb2312,cp936
"隐藏菜单和工具条
set guioptions-=T
"显示行号
syn on
set number
set ai "自动缩进
set bs=2
set showmatch
set laststatus=2 "总是显示状态栏
set cursorline
set nowrap

set background=dark
colorscheme monokai

"语法缩进
"set foldmehod=indent
set foldmethod=syntax

if has("gui_running")
  if has("gui_macvim")
    set guifont=Menlo\ Regular:h16
  elseif has("gui_win32")
    set guifont=Consolas:h16:cANSI
  else
    " linux
    set guifont=Inconsolata\ 16
  endif    
endif

"以下为配置tab和缩进
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set list
set lcs=tab:>-,
set autoread "自动读取已经修改的文件

set ignorecase "检索时忽略大小写
set incsearch
set hls "检索时高亮
set foldmethod=syntax "代码折叠
set foldlevelstart=99
"set helplang=cn

call ConfigKeymap()

au BufRead,BufNewFile Podfile set filetype=ruby

""""""" Emoji
iabbrev :t: 🍅
iabbrev :x: ❌

""""""" CommandT
function! MarkdownToogleTodo()
  let line = getline('.')
  if line =~? '^\s*-\s\[\s*\]'
    execute 's/-\s\[\s*\]/- \[X\]'
  elseif line =~? '^\s*-\s\[X\]'
    execute 's/-\s\[x\]/- \[ \]/i'
  elseif line =~? '^\s*-'
    execute 's/^\(\s*-\)/\1 \[ \]'
  else 
    execute 's/^\(\s*\)/\1- [ ]'
  end

endfunction

fun! CommandT()
  let filetype = &filetype
  if filetype == "markdown"
    call MarkdownToogleTodo()
  endif
endfunction

nnoremap t :call CommandT()<CR>
nnoremap <leader>mt :call MarkdownToogleTodo()<CR>
let g:vim_markdown_folding_level = 6

