set runtimepath+=~/.vim/config

let mapleader = ' '

source ~/.vim/config/keymap.vim
source ~/.vim/config/plugin.vim

call ConfigPlugin()
set nocompatible
set hls "检索时高亮

filetype on

"""""""""""""""""""""""""""插件相关设置
"""deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#max_list = 10
let g:deoplete#sources = {}

"""vim-auto-save
let g:auto_save = 1 "enable the vim-auto-save
let g:auto_save_in_insert_mode = 0 "do not save while in insert mode
let g:auto_save_no_updatetime = 1  " do not change the 'updatetime' option
let g:auto_save_slient = 1 "do not display the auto-save notification

"""YCM 的配置
let g:ycm_error_symbol= '>>'
let g:ycm_warning_symbol=">*"
let g:ycm_confirm_extra_conf = 1   "自动加载config

"""vim-indent-guides
let g:indent_guides_start_level = 2
let g:indent_guides_guide_size = 1
let g:indent_guides_enable_on_vim_startup = 1

""" YouCompleteMe
let g:enable_ycm_at_startup = 0

""" airline theme
let g:airline_theme='papercolor'

""" git
let g:gitgutter_enable = 1

""" cscope
if has("cscope")
  set csprg=/usr/bin/cscope
  set csto=1
  set cst
  set nocsverb
  " add any database in current directory
  if filereadable("cscope.out")
    cs add cscope.out
  endif
  set csverb
endif
""""""""""""""""""""""""插件设置结束

syntax enable
set fileencodings=utf-8,gb18030,gbk,gb2312,cp936
"隐藏菜单和工具条
set guioptions-=T
"显示行号
syn on
set number
set ai "自动缩进
set bs=2
set showmatch
set laststatus=2 "总是显示状态栏
set cursorline
set nowrap

set background=dark
colorscheme monokai

"语法缩进
"set foldmehod=indent
set foldmethod=syntax

if has("gui_running")
  if has("gui_macvim")
    set guifont=Menlo\ Regular:h16
  elseif has("gui_win32")
    set guifont=Consolas:h16:cANSI
  else
    " linux
    set guifont=Inconsolata\ 16
  endif    
endif

"以下为配置tab和缩进
set expandtab
set shiftwidth=4
set softtabstop=4
set tabstop=4
set list
set lcs=tab:>-,
set autoread "自动读取已经修改的文件

set ignorecase "检索时忽略大小写
set incsearch
set hls "检索时高亮
set foldmethod=syntax "代码折叠
set foldlevelstart=99
"set helplang=cn

call ConfigKeymap()

au BufRead,BufNewFile Podfile set filetype=ruby

""""""" Emoji
iabbrev :t: 🍅
iabbrev :x: ❌

""""""" CommandT
function! MarkdownToogleTodo()
  let line = getline('.')
  if line =~? '^\s*-\s\[\s*\]'
    execute 's/-\s\[\s*\]/- \[X\]'
  elseif line =~? '^\s*-\s\[X\]'
    execute 's/-\s\[x\]/- \[ \]/i'
  elseif line =~? '^\s*-'
    execute 's/^\(\s*-\)/\1 \[ \]'
  else 
    execute 's/^\(\s*\)/\1- [ ]'
  end

endfunction

fun! CommandT()
  let filetype = &filetype
  if filetype == "markdown"
    call MarkdownToogleTodo()
  endif
endfunction

nnoremap t :call CommandT()<CR>
nnoremap <leader>mt :call MarkdownToogleTodo()<CR>
let g:vim_markdown_folding_level = 6

